---
all:
  children:

    nfs:
      hosts:
        10.0.5.70:
          ansible_user: ec2-user

    webservers:
      hosts:
        10.0.5.94:
          ansible_user: ec2-user
        10.0.6.53:
          ansible_user: ec2-user

    db:
      hosts:
        10.0.7.123:
          ansible_user: ec2-user
